In [1]:
print("Hello World")

Hello World


In [2]:
import numpy as np

In [3]:
data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [4]:
a1.dtype

dtype('int32')

In [5]:
data2 = [0.1, 5, 4, 12, 0.5]
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [6]:
a2.dtype

dtype('float64')

In [7]:
np.array([0.5, 2, 0.01, 8])

array([0.5 , 2.  , 0.01, 8.  ])

In [10]:
a3 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
a2.shape

(5,)

In [12]:
a3.shape

(3, 3)

In [13]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [14]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [16]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
b1 = np.arange(12).reshape(4,3)
b1.shape

(4, 3)

In [18]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [24]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
str_a1 = np.array(['1.567', '0.123', '5.123', '9', '8'])
num_a1 = str_a1.astype(float)
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [32]:
 str_a1.dtype, num_a1.dtype

(dtype('<U5'), dtype('float64'))

In [33]:
[0, 1, 2]+[0, 1, 2]

[0, 1, 2, 0, 1, 2]

In [34]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])
arr1 + arr2

array([11, 22, 33, 44])

In [35]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [36]:
arr1 * 2

array([20, 40, 60, 80])

In [37]:
arr1 ** 2

array([ 100,  400,  900, 1600], dtype=int32)

In [38]:
arr1 * arr2

array([ 10,  40,  90, 160])

In [42]:
arr1 / arr2

array([10., 10., 10., 10.])

In [43]:
arr1 > 20

array([False, False,  True,  True])

In [47]:
a1[0]

0

In [48]:
a1[4]

4

In [50]:
a1[5] = 70
a1

array([ 0,  1,  2,  3,  4, 70])

In [51]:
a1[[1,3,4]]

array([1, 3, 4])

In [52]:
a2 = np.arange(10, 100, 10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [53]:
a2[0,2]

30

In [54]:
a2[2,2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [55]:
a2[1]

array([40, 50, 60])

In [56]:
a2[1] = np.array([45,55,65])
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [57]:
a2[[0,2], [0,1]]

array([10, 80])

In [59]:
a = np.arange(1,7)
a, a[a>3]

(array([1, 2, 3, 4, 5, 6]), array([4, 5, 6]))

In [60]:
a[(a%2)==0]

array([2, 4, 6])

In [62]:
a%2 == 0

array([False,  True, False,  True, False,  True])

In [63]:
b1 = np.arange(0, 60, 10)
b1, b1[1:4]

(array([ 0, 10, 20, 30, 40, 50]), array([10, 20, 30]))

In [64]:
b1[:3]

array([ 0, 10, 20])

In [65]:
b1[2:]

array([20, 30, 40, 50])

In [67]:
b1[2:5] = np.array([25,35,45])
b1

array([ 0, 10, 25, 35, 45, 50])

In [70]:
b1[3:6] = 60
b1

array([ 0, 10, 25, 60, 60, 60])

In [71]:
b2 = np.arange(10,100,10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [72]:
b2[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [73]:
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [74]:
b2[1][0:2]

array([40, 50])

In [75]:
b2[0:2, 1:3] = np.array([[25,35], [55,65]])
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])